### ISSUE TITLE
JSのコメント以降のコードが改行していてもコメントとしてハイライトされてしまう

### ISSUE THREAD

**Issue by tatsuyafukui** [dkjym/figma_ace#1]

**Comment by tatsuyafukui** [comment]
![スクリーンショット 2019-08-20 11 55 29](https://user-images.githubusercontent.com/26600620/63314098-931db900-c341-11e9-9d40-11ad68a88fb1.png)

**Comment by yuta-tsurusaki** [comment]
直したい
